name: Tests

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '**.json'
      - 'tox.ini'
      - '.github/workflows/maintests.yml'
      - '.github/workflows/prtests.yml'
      - '.pre-commit-config.yaml'
      - 'scripts/requirements.txt'
      - 'scripts/requirements.dev.txt'
jobs:
  no_extra_fields:
    env:
      HORDELIB_CI_ONGOING: "1"
      TESTS_ONGOING: "1"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r scripts/requirements.dev.txt
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
      - name: Run unit tests
        run: tox -e no-extra-fields
  build:
    env:
      TESTS_ONGOING: "1"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r scripts/requirements.dev.txt
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
      - name: Run validation
        run: tox -e validate-sd

  verify-styles-valid:
    # We need to make sure the unit tests in `Haidra-Org/AI-Horde-Styles` would pass with these changes

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10"]

    steps:
      - name: Checkout AI-Horde-Styles
        uses: actions/checkout@v3
        with:
          repository: Haidra-Org/AI-Horde-Styles

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install AI-Horde-Styles requirements
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r requirements.txt

      - name: Run AI-Horde-Styles unit tests
        run: |
          export HORDE_MODEL_REFERENCE_GITHUB_OWNER=${{ github.event.pull_request.head.repo.owner.login }}
          export HORDE_MODEL_REFERENCE_GITHUB_BRANCH=${{ github.event.pull_request.head.ref }}
          python -m unittest discover tests
