name: URL Validation PR

on:
  workflow_dispatch: # Allows manual triggering of the workflow

  pull_request_target:
    branches:
      - main
    paths:
      - '**.py'
      - '**.json'
      - '.github/workflows/url_validation.yml'
      - '.github/workflows/url_validation_pr.yml'
jobs:
  required-label-job:
    runs-on: ubuntu-latest
    permissions:
        issues: write
        pull-requests: write
    steps:
        - uses: mheap/github-action-required-labels@v5
          with:
            mode: exactly
            count: 1
            labels: "ready-for-review"

  url-validation-pr-job:
    runs-on: ubuntu-latest
    needs: required-label-job

    steps:
    - name: Checkout PR repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        path: pr

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r pr/scripts/requirements.txt

    - name: Run URL validation script
      run: |
        python pr/scripts/urls_valid.py pr/stable_diffusion.json
