name: URL Validation

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

  workflow_dispatch: # Allows manual triggering of the workflow

  push:
    branches:
      - main
    paths:
      - '**.py'
      - '**.json'
      - '.github/workflows/url_validation.yml'
      - '.github/workflows/url_validation_pr.yml'
jobs:
  url-validation-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt

    - name: Run URL validation script
      run: |
        python scripts/urls_valid.py stable_diffusion.json
